# Percorso della cartella o del disco di cui fare il backup
source_path = "/Users/lorenzoricci/Documents/Politecnico di Torino/Web App 1/Esercizi in classe"

# Percorso di destinazione dove salvare il backup
destination_path = "/Users/lorenzoricci/Desktop/MyBackup"

# Tipo di backup: "full_disk", "directory", o "selective"
backup_type = "directory"

# Lista delle estensioni dei file da includere nel backup
# (usato solo se backup_type è "selective")
extensions_to_backup = ["txt", "doc", "docx", "pdf", "jpg", "png"]
